[dependencies]
base = "0.12.0"
itertools = "0.2.1"
datetime = "0.3.0"
test = "2.0.0"
xtended-text = "0.3.0"
xtended-random = "1.0.0"
dao-proposal-engine = "https://github.com/edjCase/motoko_proposal_engine#0402e245babf68cd3a9ad8a1ead4087181f2268f"
