[dependencies]
base = "0.13.0"
itertools = "0.2.2"
datetime = "0.3.0"
test = "2.0.0"
xtended-text = "0.3.0"
xtended-random = "1.0.1"
dao-proposal-engine = "https://github.com/edjCase/motoko_proposal_engine#f99e41c0cf00de00086e3c3c7c61a5fc75a51c91"
certified-cache = "0.3.0"
