[dependencies]
base = "0.12.0"
itertools = "0.2.1"
datetime = "0.3.0"
test = "2.0.0"
xtended-text = "0.3.0"
xtended-random = "https://github.com/edjCase/motoko_random#24aed41c63fa3091b269faa0353e0a5a86282b4e"
dao-proposal-engine = "https://github.com/edjCase/motoko_proposal_engine#44f75c9b80da99682ae2b452ad06db03fc25e167"
