[dependencies]
base = "0.10.4"
itertools = "0.2.1"
datetime = "https://github.com/edjCase/motoko_datetime#28e765bf5bb6b9d75a9416713ab863bea0d4a61f"
ic = "1.0.1"
test = "1.2.0"
xtended-text = "0.2.5"
icrc3-mo = "0.2.3"
icrc7-mo = "0.3.1"
icrc30-mo = "0.3.1"
ic-certification = "0.1.3"
vector = "0.2.0"
random = "https://github.com/edjCase/motoko_random#5aa3841b20a5e9f722475743febb47349ae6559b"
