[dependencies]
base = "0.11.1"
itertools = "0.2.1"
datetime = "0.3.0"
ic = "1.0.1"
test = "2.0.0"
xtended-text = "0.2.5"
ic-certification = "0.1.3"
vector = "0.3.1"
xtended-random = "0.1.0"
dao-proposal-engine = "0.1.0"
