[dependencies]
base = "0.11.0"
itertools = "0.2.1"
datetime = "https://github.com/edjCase/motoko_datetime#e08e39020fa4ac1871f3c17fc0e96e0b3c898c9f"
ic = "1.0.1"
test = "1.2.0"
xtended-text = "0.2.5"
icrc3-mo = "0.2.3"
icrc7-mo = "0.3.1"
icrc30-mo = "0.3.1"
ic-certification = "0.1.3"
vector = "0.2.0"
random = "https://github.com/edjCase/motoko_random#0a02c4b819fb29eee9b74ebb2e5fd1ccf351206e"
