############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Links"
hasChildren = true
weight = 3

[[main]]
parent = "Links"
name = "Wiki"
url = "https://github.com/edjCase/daoball/wiki"

[[main]]
parent = "Links"
name = "Taggr"
url = "https://taggr.network/#/realm/DAOBALL"

[[main]]
parent = "Links"
name = "Twitter"
url = "https://twitter.com/daoballxyz"

[[main]]
parent = "Links"
name = "Blog"
url = "https://mora.app/planet/a46fs-ryaaa-aaaan-qdcyq-cai"

[[main]]
parent = "Links"
name = "Github"
url = "https://github.com/edjcase/daoball"


# footer menu
[[footer]]
name = "Contact Us"
url = "mailto:daoball@edjcase.com"
weight = 1
