############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Wiki"
url = "https://github.com/edjCase/daoball/wiki"
weight = 3

[[main]]
name = "Blog"
url = "https://mora.app/planet/a46fs-ryaaa-aaaan-qdcyq-cai"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Whitepaper"
url = "whitepaper/"
weight = 2
