
import { Item } from "../ic-agent/declarations/main";
import { decodeBase64ToImage } from "../utils/PixelUtil";

export const items: Item[] = [
    {
        id: "power_gauntlets",
        name: "Power Gauntlets",
        description: "A pair of gauntlets that grant the wearer immense strength.",
        tags: ["armor", "enchanted"],
        image: decodeBase64ToImage("MAAAAD8bCjkcADggDisWDSgIBVg3ILN8RYFSK51jMHVDIU0qFbKbgNSyfpNXKlQuFrJ4QGQ5G7x+RKFbJEgmEjEUFItOIKhlKz0oHKBdKXtHI5BPIoZPKV8xGjkjFWI/JnhJKHBCI6JrPXxRLoJNI5ldMGpHJXNGJi4KBqRYHoRXLyoVBEYjCFA8L5ViOiQSAJcB/wEAD/8BAAIBDP8BAgEDAQQBBQz/AQIBBgEHAQgBBAEACf8BAAEGAQkBCgEDAQAL/wELAQwBDQEOAQ8BBAn/AQQBBwENARABEQEECf8BBAEGAQcBDQESARMBCgEUARUBAAX/AQIBFAEWARIBDQESARcBCgEBAQUG/wEFARgBDAENARIBGQEXARYBBgEDAQQBAAP/AQABFAEaARsBDQESARwBEAEXAR0BHgEABP8BBQEGAQcCDQEcAR8BGQEQAREBBwEUAQQC/wEAAQMCBwEXAQ0BIAEGAhABFwEhAQME/wEfAQwBDQESAQ4BIgESASMCCgEiAREBBAL/AQABBgESASIBDgEfASIBEgEkAQ4BEAElAREBAQP/ASYBDQESARABBwENARIBBwEnAQoBDgEkAQQC/wEoASYBDQEOAQsBBwMSAQ4BCAEOAQoBAQP/AREBEAEWAhIBEAIXAQgBEQEaASEBBAL/ASgBBgESARkBDwESARcBKQETARcBBgIRAQED/wEUASABCQMXAQ4BGQEhARQBIQEGAQQC/wEAARQBCQEZAQoBEgEXARsBFgEaAR0BCgEeARUD/wIDAQcBDQEXAQ4BEwEkAgoBDwEDAQAD/wEUAQ8BIgEJASQBGwEWARkBEAEZAR4BFQEAA/8BAAEFARgBKgEOARsBGgEQASIBHQEPAQME/wEUAR0BGgESAQ0BDgERASEBJwEUARUBBQb/AQQBCwEKARkBFwEcAR8BEQEKAQME/wEUASIBDQEpASEBKgEWASEBCwEDAQUI/wEDAQ8BGgEWARABIgMKAQMBAAH/ARUBJgESAQkBDQEcAh0BCwEeAQUK/wEUAR0BDgEXASQBBwIbAREBBAErAR4BDAISAQkBIQERAR0BHgEVC/8BLAEdAQkBDgEKARwBEgElASECHgEtAQ0BEgEHARsCHQEPARUM/wEAAR0BCQESARMBLgEfASUBDgEGARgBDAEXASoBJgEkAREBCgEeAQQN/wERARkBEgEbARoBIwEeAgQBLwIEAREBHAERAgoBAw7/AQ8BHQEqARkBCQEeAQQBKwEFAQACBAEDASEBGwEKARQBAw7/AQABCwEPARQBCwEEAS8E/wEAAQQDFAEDARUQ/wEvAgQI/wMEAQDIAf8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "eagle_eye_amulet",
        name: "Eagle Eye Amulet",
        description: "An amulet that enhances the wearer's vision, perfect for spotting enemies from a distance.",
        tags: ["jewelry", "enchanted"],
        image: decodeBase64ToImage("L3dXLX5hPnBAIH9VNohjPlQ+HolcM6B1Q7F+Q4tuSklJJG1bN1VVOW1rVGlQLX10XY6OhIeEeJyhm3ZjTIB+bqq4uKWnpaSdjaCQaW9tYdOQRrKlXnt4aIFmSt+6XdapUsKVVuffqOGxaNmeTI6Ld+balHNqPtKCNuPKcNvMb72uY8WNTL90M8qbUtClWwH/AgABARr/AQIBAQH/AQIBAwEEAQUZ/wEGAQEC/wEEAQcBCAEAF/8BBQEJAQEC/wEAAQQCCBb/AQoBBAEGAQsD/wEFAQYCCAEFE/8BCAEHAQEBBQX/AQIBAAIHAQoR/wEDAgQBCwf/AQUBBgEHAQQBCwX/AQwBDQf/AQECBAEDAQ4J/wECAQYCAwEIA/8BDwIQBf8BBQEOAQcBAwEAAQ4M/wECAQYBBwEIAQsBCgERARABEgH/AQUBAgEGAQQBBwEDAQgBAA//AQMBBAEGAQgBCwETAREBDQH/AQ4BAQEIAQYBBwEDE/8BBQELAQQBFAEVAQUB/wEHAQQBDgEFF/8BFgEQARIBFgEQAQwBBRj/ARcBFQEWARgBEgEQAREBGRj/ARQBFgEXARoBGwEVAQ0BDBb/AQwBHAEQAR0BBwEeAR8BIAEKAhAV/wEMAREBEAEVASEBIgEjARoBJAEWARUV/wEWARABBgElASECJQEjARgBFQESAQUT/wESAREBDAEGASUBIQEbASYBHgEnAREBDQEME/8BDwEkARABBgEiASgBKQEqAR4BJwEXARQBCxP/AQwBFAESAQkCHgEoASUBHgEnAhIBDRP/AQwBEQEWAQ8BFwErAR4BHwEnARMBEQEQAQ0T/wEMARECFQEHASwBLQEuARoBDgEVARYBFRL/ASQBEAEMAQ0BFQEZAQYBCAEFARwBEgEQAQwT/wEFARkB/wEMARkBFAERARYBFQEUAQwBDQEFF/8BBQH/ARABFQESAQUBDAEFGv8BHAEWARkB/wEFG/8BFQEWARGvAf8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "divine_emblem",
        name: "Divine Emblem",
        description: "An emblem imbued with divine magic, perfect for cleansing corrupted energies.",
        tags: ["jewelry", "enchanted", "cleansing"],
        image: decodeBase64ToImage("FSwnG1Y3CYdWByYmJmM+Cp5kERomJtueKZ9kAdvXl0ozGa1xEuagQfXZUPjlTNnGfC0kD0AsCfHuwseOIjMzM23/AQABAQICAQEBAxr/AQMBBAIFAQQBBhr/AQMBAgIHAQIBBhr/AQMBAgIHAQIBAxr/AQMBAgIHAQIBAxr/AQMBAgIHAQIBBhr/AQMBCAIHAQgBBhf/AgkBBAEKAQsCBwELAQoBBAIJFP8CCQIEAQwCDQEMAgQCCRT/AgQCDgEIAg8BCAIOAgQO/wIAAhABAAIQAQQCDgECAg8BAgIOAQQBEQQQAgAI/wIBAwIBCAELAQwCCAESAwkCCAEMAQsBCAMCAgEI/wICARMEBwENAg8BCQISAQkCDwENAgcBEwIHAgII/wICBQcBDQIPAQkCEgEJAg8BDQUHAgII/wIBAwIBCAELAQwCCAQJAggBDAELBAICAQj/AQMBFAEGAQMCBgEKAQQCDgEIAg8BCAIOAQQBCgUDAQYO/wIEAg4BCAIPAQgCDgIEFP8CCQIEAQwCDQEMAgQCCRT/AgkBBAEKAQsCBwELAQoBBAIJF/8BBgEIAgcBCAEDGv8BAwECAgcBAgEGGv8BAwECAgcBAgEGGv8BAwECAgcBAgEDGv8BAwECAgcBAgEGGv8BAwEEAgUBBAEDGv8BBgEBAgIBAQEDbf8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "artificer_toolbox",
        name: "Artificer Toolbox",
        description: "A toolbox imbued with magical properties, perfect for repairing and creating gadgets.",
        tags: ["accessory", "enchanted"],
        image: decodeBase64ToImage("MFVVqlVVgH6OvXKCsnGAp4B/h6GhnBsZFmpyk4uKiYaLloWNoklDMomCeHR0b1RVXIJ9bnZrW1NTTUCAgIByU6yFTlFLOXdlP5WAVYmTvUZddGJILo9zS8Ona7SmenJSLYhySLecaKyNV4RaMVlBLGBUNiwdFp2SaoCAv6KLXb2aX21kQ6iWcpNiJ59uOY9YKkv/AQABAR7/AQIBAwEEGv8BBQIGAf8CAgEEGP8FBgH/AQcBAgEIFv8DBgIJAQYBCgH/AQMBBAP/AwYE/wELAQQI/wEMAwYBCQEFAQ0CBgH/AgQC/wQGBP8BAgELAQMH/wEJAgYBCQENAQUBDQIOAQEBAwEEAf8DBgEJAQ4CBQP/AQsBAgEEBf8CBgIOAQ0BBQENAQ4CDwEFAQIBAwMGARACEQIGBP8BAwEEBP8CBgEJAQ4BDwMOAQ8BCAICAQQBCAMGAg4DBgH/AQcCAwEEBf8BBgEJAQ4BEQISAgkBDwEEAQMBAgEIARMHBgEJAf8BDwEDAQQBAwEABP8CDgERAQ8BBwEMAREBFAEVAQcB/wICAf8GBgEFAQ4C/wIDAREB/wEDAQAC/wEHAggBAwL/ARYBFwEYARcB/wIZAf8EBgEJAQ0CDgEEAQMB/wEHAv8BAwETAv8BBAEBARoBCAL/AQcBGwEXARwBDAL/AgYBCQEQAw4BEgEIAgICBAb/AQgBAwEEAQgC/wEdAR4BHwIgASEBIgIGAQkBDgERARwBIwH/AQMDAgEEARkBAgj/ASQBHgEhASUBJgEbARcBGAMGAQUBDwEmASUBIAEVAwMCAgEaARMG/wEnAh0BHgEnAwcBHwEXAgYBCQEOARICBwEgAR0BCgEEAhkBKAj/ASkBKgEiAR0BIgEMAgcBJgMGAQ4BEAEnARYBDAErAR0BIQEdASwBAQn/ARgBFQEtARUBKgEhAykBHgUdAioBIgIqARUBIgEmCf8CFQEbAR8BLgQdASoBLggjAR8BDAEuASQJ/wEYAS4BGwEfAS8BHQEuAR8BIwEuAR8BGwMfARsEHwEkASMBJAn/ASIBLgEfAi8BKgEuASQFLwIuAy8CLQEfASMBJAn/ARUBLgEfAi8BKgEuASQCLwItAS8BHwEjAi8DLQEfAS8BJgn/ARUBLgEfAi8BKgEuASQBLwQtBC8CLQIvARUBJAn/ARUBLgEtAi8BKgEuAR8CLwQtBi8BFQEiASYL/wEtASMBLwEiAi4BLwEfBBsBJAMbAR8CKgEVASYL/wEkASMBLgUVAS8DIwEvBS0CLgEHDf8CLgIVASIBLgEfGv8CLgEVAS4BLQEHUf8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "dark_essence_vial",
        name: "Dark Essence Vial",
        description: "A vial imbued with the essence of darkness.",
        tags: ["jewelry", "enchanted"],
        image: decodeBase64ToImage("K6KMZpZ7VoluTX5jSVdLPGZnaqaLYp6CW5J0UYl1W0hKXKOttIF0bIt7bHpqYI+Cd4aGiXmInoWTqXmCjoSNl4uYpXB5imh0iFleb2l0g1VhbzY7QTQ4PlxndmJug0pMTmFsdzw/UUdSXTo7SGNwekxWY1FZbElMZjE0O0FDWCwuMY0B/wEAAQEBAAECAQMBBBn/AQUBAQEGAQcBCAEJAQUBChf/AQUBCwEMAQ0BDgEPARABEQESF/8BEwEUAQsBFQITAhYBFxj/ARgCGQEVAxoBGxj/ARwBGQEdARkCHgEKGf8BGwELARUBFgEXARMBHxn/ARsBFQEUAQsBHgEgASEZ/wEfAxUBGQETASIX/wEjARwBCwEUARUBFAELAREBJAElASEV/wEkAQsBFQMLAhUBEQEeARoV/wEUAQsBEQELARUBCwEVAxkBHRX/AR0BCwEmARYBHQEYARUCIwEYARYV/wEdASIBHQEnARwBKAEdAQoBGwEjARYV/wEkASkDKAEqAScBHQEpASABGhX/AhgBJgEnAiMBKAEnASkBJQEaFf8BIAEYASEDIwEpASEBKQEeAR0V/wEkAR0BKAEnASkBKAEmASMBKQEhASYV/wEWAR0BKAEmAScBKgIoASkBKAEZFf8BJAEmASgBJgEYASkBIwEcASkBKAEdFf8BGAEnASEBJwEYAScBIwIpARwBHRX/ASUBHQEoAiMBIQEpASEBKAEpAR4V/wEmARQBCgMjAScBIQImAR0V/wEKARYBEwEUAQsBFQIRARcBCowB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "boots_of_sneaking",
        name: "Boots of Sneaking",
        description: "Enchanted boots that make you move like the wind.",
        tags: ["footwear", "enchanted", "stealth"],
        image: decodeBase64ToImage("MRsaGzQxODY2OGpiaVFPW0VESpeVmzIsMEA/Qx4dHisrKzw7QlVVVWhodCkiH4CAgCQgHX16hUtJR2RkbWxreayroV9OSkFATVtYY4qMlnNyfkE6PT0xMVdWXRoaET8/Pc/NyDcrIkA2MF1TWV5IPzcrI0oxITopHU81I1E5LUUzKlg8K2pOPDEnHlVFQlxEOWBAKq8B/wEAAQEBAgIAG/8BAAEDAQQBBQEGAQcBCBX/AQkBAAEJAQEBCQEKAQEBCwEGAgwS/wEJAQABAgENAQIBCwEOAQkBBAEIAQECDgEPAQkR/wIQAREBCwEKAQcBCgEJAQoBEgETARQBCgEQARUQ/wEJARYBAwEBAhIBBQEXAQoBFwEHAQUBEwEGARIBBgEJD/8BCQERAQEBCwEPAQ0BCAELARACAQMYARIBCgEJD/8BCQETARgCAwEEAQgBDgEJAQEBCwMTAgkQ/wEJAQIBGQEUARcBBAEKAgkBAQEHAQUBEwERAQ4T/wEJARMBBwELAQECCgEJAQcBBQEYAQYBCBP/AQABGgEbARwBAQEKAQkCCgEFAQcBHQEYAQkR/wEAAR4BFQEBAQsBDQEKAQkBDQEBAQICDQERARgBCRD/AQIBGgEGAQECFwELARACCwEXARMBEQEZARMBBwEeDf8CCQEXAQwBCwEEAQEBAgEKARABDgEKARcBEwENARkBEQETARgBCgz/AQIBDQEZAREBEwEYAgsBCgEJARABDgIBARgCGgIZARMCCQf/AQABDAEfAQYBFQERARQCBAEUAgEBCgEJAQoBAgEHAQsBBAEYAxkBEQEMAQkG/wEAASACBgERARMBGAEWAQQBCwIHAQkCAAEhARwBIgEBAQsCEQEUARkBFQIeA/8BAAEKAQUCBgEZARoCIwEkAQEBBwElASYBEAEKAQABEAEnASgCHAELARcBBAEYAREBFQEfA/8BAAESASABEQEaARQBGAEjARsBKQElARABCQIAAv8DAAEQAQ4BKgIpASsBLAEmARAE/wEtASQCLgEvASQBMAEoAScBAAv/AQkDAAEJAQABCQT/AQkFIQEJ1wH/"),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "nature_pendant",
        name: "Nature Pendant",
        description: "A pendant imbued with the essence of nature, perfect for cleansing corrupted energies.",
        tags: ["jewelry", "nature", "cleansing"],
        image: decodeBase64ToImage("LjdENh4iHV5uWh4nIjM9MkpYRxofGpSuiik2J4CYeBIiF0pvPBUlHT1tKz9gMz1kLx42Hi5PJmGjOjBUKTRbLiI9I12SPlCLMkBpNDtuNGSZTVeJQitRHqLcenGvUk99PDdhMBo1Gx0sG0pzN1mKSRgoGHWxR36vYVCGOSdLI0F0OyVEH1R9R1CJPQz/AgAC/wEBAQICARj/AgAC/wEDAQQBBQEGGP8CBAL/AQYBBwEBGf8BBAEAAv8BBgECAQYZ/wIAAQEB/wEBAQUBAwEBGP8BCAEJAwYBAgEDGf8CBQL/AQgBBQEDGf8BAQEFAQYB/wEFAQQBAxn/AQEBAgEGAQoBBgECAQYZ/wEGAQQBAAEFAQIBBQEGGv8CBgEJAQIBAwEBHP8BAAEHAQEb/wEBAQgBAgELAQYa/wEDAQwBDQEOAQ8BEAEKGP8BBgERARIBEwEUARUBFgEUAQMW/wEBAQ8BFwEYARkBGgEbARMBEgEYAQoU/wEDARQCHAEUARoCHQEeARMBHwEgASES/wEBARoBGwEiASMBJAQdASQBHgIXASUBARD/AQwBDgEiARgBJgEdARcBHgEnASgBJwEYAh4BKQEiEf8BCgEVARoBKAImAQ0BJwEbASoBKwEZAQ8CEBL/ASUBIgEnARoBJgEXASwBJAEtARQBGQEQFf8BJQEVAR8BKAESARwBDgETAREBJQEMFv8BDAEKARMBEAEfASEBIgEKGf8BBgEiAQoBIgIKjQL/"),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "boots_of_quickness",
        name: "Boots of Quickness",
        description: "Enchanted footwear that makes you move like the wind.",
        tags: ["footwear", "enchanted"],
        image: decodeBase64ToImage("MioqKjgwJkU6LEA3KUU+L1JCLXFbP3ZcPVdINGZcSGRROn9iQFdGMGNVRmtTOquQZ15POnNkTJB2U42AZIJlRHdhRm9kTqCMZn9qTYZtTG9YO09ENIdpR7Wdcn9yWntvV4d+ZKWIYFJHNzc3JIh1WHtvVpt9Vq2TaqmLYqODXHJgSJZ3UF9XRIp8X5t5UoBVVVxRQIZ5YIgB/wEAAQEFAgIDAQEBAwEEAQICAwEADv8BAAEBAQQBBQEGBAcBAgIDAQgBBwEGAQUBAgEBAQAN/wEDAQkBCgELAQcBDAIFAQsBCAENAQoBBwEFAQwCDgEIAQMBAQz/AQMBDwEQAgUCAgIFAREBEgEKAwUBAQECAQwBAgEEDP8BAwETARABCAEMARABFAEHAQwBFQEKARABCAIMAQoBEAEHAQkBDQEWARcBEAn/AQEBBAEYARkBFAEaAgoBGwMYARkBEgEcARoBBgEQAR0BFwIdAR4BBQr/AQMBCAEMAQUBDgEQAQoBGAEEAQUBDAEIAQwDEAEfARABIAIdAQ0BBQEACP8BGwEZARUBBQEMAQgBBwEYASECGQEcAQsBGgEDAQEBGwIiAQkBDQEIAgUI/wEBAQICBQEcAQsBBgEYARIBFAELARUBBwEOAQIBAQb/ARsBIgj/AQEBBAEGAQUBAgEKASIBGAEDAgYBEAEaAQ4BAwEBEP8BIwEbARUBFAEIAQcBAwEGASQBGQEIAQUBDAEOAQwBARD/AQEBJQEmAQsBGgEOAQUBEAEVARwBAgEaAQ4BBwECAQEQ/wEBAQoBFQEOAwwBEQEnARkBAgEUAQsBCAIBEP8BAQEDAQ4BBwECAQcCAgEbAQUBGgECAgwBAQEAEP8BAQElAR0BFAEIARABBgEYASgBFAEcARQBBwEKAgEQ/wEBARABBgIHAQ4BBQEYAR0BKQEZAhQBDAEDAQAO/wIBARABKgEYAQsBDgEMAQMBCAEGAQ4BGgELAQcBBgEFAQEN/wEbAQEBBAEXASQBBwELARQBBQEKASoBEgEUAQcDCwEMAQEK/wEjAQEBAwEiARABGAEVARcBFQIOAQEBCgENAQgCBwErAQsBBwEFAQAJ/wEIAQMBAQEZARIBJwEVARoCDgEIAQMBBgEKARcBEgEHAwsBBQEBAQAI/wEjAQMBIQIdAQ8BKAEZARwBBwIQAikBIQESAQgBDgEcAgoBBQEBASwBLQETAi0E/wEBAQMBLQEnASsBHAESARwBCgEVAQ8BJwEoAi4BKwEUAQsBDgEDAQABAwEWAS0CIAEXARMDLQEvASMBAwEEARABDAEbAQwBBQEBARIBHQEmARkBHAEUAQ4CCAEbAgkBFgItAhMBFwETAiABLQEkAv8BAAEWASUCHwEwAQABBAIiARsBAgEDATABHwElAR4BEwEtASABMQQtAS8O/wMTASABLQEgcP8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "treant_bark",
        name: "Treant Bark",
        description: "A piece of bark from an ancient treant, surprisingly sturdy and protective.",
        tags: ["nature", "armor"],
        image: decodeBase64ToImage("LZ+PZ3d5SoeGVXxrTIZ2UZF/XERDRI+NXW1eQ1dLNW5xUVphUXZuVV9ZVjR+UB2JRUhRVDlLZi+TVUu8YFqxUHeGTkNQbVVOR2lhUXLDXpbjkobVeipAald1UiaYSiqoSjGtToXJc5CWXDhIc3fFZX+eXHCUVFG7V33Kbz9EUkhIUC88cVxUSrEC/wEAAv8BAAEBGf8BAgEDAQQDBQEGFv8BBwEAAQUBBAIIAQUBAwEEAQgBCQH/AQUBCA7/AwUBBwEEAgMCCAEJAQQBCQEKAQsBAQEFAQwBDQ7/AQABBQEEAQUCAwEIAQMBCQEKAQ4CDwEOAQQBCAEQAREL/wEHAgABBAEIAQkBAwMEAQgBCgEOARIBEwEUARUBAwEJARYBFwEQCv8BBQEAAQQCCAEDAQwBGAELARABDgEPARkBGgEbAQcBBAIIARcCFgEcCf8CBQEEAgMBHQIOAR4BHwEgARMBGwEhASIDCAENARYBIwz/AgQBCAEdARIBJAEbAhkCGwElAQIBAwIIARACIw7/AQQBCgEOASQBGgEhAQcBBAEmASIBCAEJAgMBEAIjD/8BDQEOAScBKAEZAQEBAwEIAQQCAwIIASkCIxH/AQ8BFAIEBAgCKgEpAiMBHBL/AQ8BJgEFAgMBCAEJASoEIwErFP8BFwEsAQwBBgEqASkBIxr/AREBFgMjARyQAv8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "endurance_belt",
        name: "Endurance Belt",
        description: "A belt that magically enhances your stamina. Just don't ask where the energy comes from.",
        tags: ["accessory", "enchanted"],
        image: decodeBase64ToImage("KS4kH0g5K5mJbbOTcZuAYqh8VqqqgEIwIlVKPGxfTY1rT1gvHV81H3dQNHJiTXlpUiwhFiEaFIRhQ2pGLqNyTZdnQsCacryfemNDLKyGYWE+KI1cOkwzIVY4JFMwIk44KHFTO4ZaPKt0TGg/JUEsHTIiF4FTM6qDXEUwIuUC/wEAAgEBAgIDAQQBBQIDAQYGAwEHAQgCAQr/AQgBCQIKBAsKDAENAwoBDgEBCP8BDwECAQQBAAEQAhEMEAERAQQBAgEEARII/wETARQBFQEWAxcBAwIUARgBCAEDAQkBDgIUARkCAwENAhMBGgj/ARMBFAEVARsBEwIcAR0BCAEeAR0BHwIUAQcFEwINARMBGgj/ARgBIAIIAwMBBAEgASEBBwEKASIBEwEQASMDEwQNARoG/wEPAgQCBQEUAhsBIQENARoBDAEKASIBIQEcAQ0BHwEkAQwCIwITASMBJQb/AQIBFAIbASYBDQEMAR0BHgIQASUBFgEiAQ0BHgEbARQBHQEQBCUBEAf/AQgBDQEjARoBEAElAhEE/wEbARQBJgEeASYBFAEnAQEY/wEQAhwBEAEoAQ0BIgEWAQoc/wEkASYBFAEZAScc/wEoASEBIgEWHP8BEAEfASEBIgEWHf8BHAEbARQd/wEeAh3HAf8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "rare_herbs",
        name: "Rare Herbs",
        description: "Exotic plants with potent alchemical properties. Handle with care!",
        tags: ["medicine", "plant"],
        image: decodeBase64ToImage("L5+fYJGYZ6OscZysZLW5fXuHU4OaTqSubWt9Ro+aYKGyaZ+wbZaWaa24dltwO42pU3OGTGJ2QkdUNamvdJGqV3qQTVhsO4uXXYWhTlZnO2RvIHePSlNgOoebVHKMRX2RUW2HQV51OHOQRHqXRoydWYeUWGWBOY6kVVVtNGR5O2uGPXiOSTNmM2yAP2p8P5UB/wEAAQEBAhz/AQMBBAEFAQABBhr/AQcCBAEIAQkBAxn/AwQBCgEIAQsBAxj/AQwBDQEEAQoBBgEOAQMBCxj/AQwBDQEDAQ8BEAERAQkBAg7/AQ0BEgf/AQEBEwEEARQBFQEWAREBAg7/ARMDBAb/ARcCDQEYAQgBGQERAQIO/wESAQQBFAENARMBGgT/AgQBDwEbARYBHAEBAQ0O/wESAQQBFgEUAQQBDQT/Ag0BGAEIARkBEAEAAQwO/wEaAQIBCAERARQBBAETAQEC/wEFAR0BHgEWAQgBHwEWEP8BCAEKARABIAEKAg0BAgL/ARYCEQEGASAE/wEFARMM/wIDARkBHgEPAQ0BAgENAf8BBQEYASABIQL/AQ0BBAETAQIBBAz/ARQBDQEIARkBGwEDAQQBDAH/AQwBCgEgARIB/wEHAgoBFAEIAQMI/wECASID/wEHAQUBHAEOAQYBDQELAf8BCQEDASMB/wINAQMBBgERAQgBDwj/AwMC/wEPAQkBJAEOAREBHwEAAQ4BIAEdARoCDQEUAQ8BEQElAQoBGAj/ARQBBQEIAQMBDwEeASYBBgEDAQgCEQEWASABJgELAQ0BFAEYAQgBEQEDARUBEgj/AR4BJwElAQgBDwEDARYBIgEfAQ0BAQH/ASYBIwELAQQBCgEPARABFgEJASMBKAr/ASkBFAEfAR4BJwEUARcBIQEgAQ8BAwEWASIBHQEPAQYBCAERAQMBGAEqC/8BEgEpAQoBBwEAAREBEAEDAQ4BHQEDASgBJgEYAQYCEQEkAScBKQEcDP8BEgErARQBDQEBAQ4BFwEJAREBBgESASYBBgEbARABJAEPASABKA7/ARoBIAEjAQMBCQERASUBJAEYARIBJgEaARcBFAEGASABIRD/ASwBDgEgARQCCQEMASIBEgEmAQIBAwEjASoBDhL/ARIBKQEtARQBDQEBASYBGwEmAR0BFAEqASEV/wEWAS4BHQEKARwBBgEmAhgBKQESFv8BHAEhAScBJQEYASYBIwEiAQ4Y/wESAQgBDQEoARkBCgEpGv8BKAEHARIBHAEPASMM/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "nature_crystal",
        name: "Nature Crystal",
        description: "A crystal infused with pure natural energy. It hums with the song of the forest.",
        tags: ["crystal", "nature", "enchanted"],
        image: decodeBase64ToImage("LDmcMjeUJkTHOT6/OD27MnfcZnPaYj2wNzOIIk3BQn3aaEfJPEGwO4PobzeFNz6sM0S3O0KpNpfke5XdfEKjNi+VFDuZLE21PpjtgGHUUaPziZ/whWjZVzeYKz+0NEm0O5TrfX3KaXG+XmC3UCpwIZDWemq9WV2tTzCGFzGXCSp4GD61OWj/AQABAR7/AQIBAwz/AQMR/wEDAQQF/wEFAQYF/wEDAf8BBwICCv8DAgEIBP8BBwEJAgoBCQT/AgMB/wICCv8BAgILAQEE/wEMAQkCDQELAQ4D/wICDf8DDwT/AhABEQESARMBDwEJARAD/wEUC/8BFAEDAQQE/wEVARYBFwIJARgBEgEXARABDwEBBf8BAAEDB/8BBwECAQMD/wIBARYBEAEZAQUBGgEbARwBDwEWAR0BAQT/AQ8BCwf/AQABBAEeA/8BHQIWAQ8BFwEbAhoBDQEZAR8CHQEBA/8BBwEeDP8BEAEfAR4BAAERAQkBIAEhASIBIwEZAR8BAQIIAQEP/wEkAQkCGQERAQkBHAEFAQACCAEJAR8BAQEkAQgBAQEkDf8BCQELAQ8BCQEcASABBQEZBAsCCAEVAQECJAIBC/8CBgEFASUBEgEYARsBJgEUBAsBCAEUARcBHQEUARcBCQEAAQEJ/wEOAQYBBQEKASUBEwESASABJwEOBAsBCAEUAQkBHQEMAgkBFAEBCv8BJwEWAR0BJAEIARYBGQEUAQgECwEkASgCKQEqASQCAQz/AwgBKgEkARYBHwEjAQYBCQEeAQgBFwEPARUBJAEqAggP/wEBASoBJAEIAREBCQEGARkBHwEoARABAAEIASQCCBH/AgECCAEWAhkBCQEpAQECCAEBAQgC/wIPDv8BCAIBAiQBFgEAAR0BKQEkAQgBAQEIAv8BAAECAQMP/wEIAQECJAEIAhQBKgEkAggD/wEHAgMR/wEBAQgBJAEJARcBJAIIEf8CAgb/AQgBAQIJAQEBJAP/AQMCCwEQC/8CHgL/ARABAwP/AQECEQEIBP8BHgEDAisO/wEeAQMBAgEeA/8CAQP/AQABAwEeEf8BAgEDAQQJ/wEeAQIBAxH/ARABKwr/AQABKwEHaf8="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "mysterious_seed",
        name: "Mysterious Seed",
        description: "A seed of unknown origin. Who knows what might sprout from it?",
        tags: ["plant"],
        image: decodeBase64ToImage("K92tjxIQEZJjRUsyIh4WEzwrI086LYNcRY5hSp9uUn1YQYVpVrWOcm9YTCgeGmtLOoJaPq18W2BENVg7LG9IL7SBZEQsHlo3I3lPN3dXQraSbVxAK042KciMZ107KlcyGTIlH2lHL1UzH8SNZG5NNkAuJHJLNiobEy0jHS8dEzwlFvIB/wEAFP8BAQECAQMBBAEBG/8BAQEFAQIBBgYBBf8BABH/AQECBwEIAQkBCgELAQwBDQIEAQEU/wEBAQ4BDwEQAQIDEQEMAQkBEgEBFP8BAQETARQBCQEPARQBEAERARUCDAEPAgES/wEBARYBFwEYAQIBGAEDARkCCQEMARoBGQEBEv8BAQEbAhcBAgEJARABHAEPAQkBFQEdARoBEgEBEf8BAQEZAR4BHwEUAQIBEQEGARYBGAEJAREBDAERARMBARD/AQEBGQEbARYBHwEQAQkBCAEbAR8BEAERAhUBGQEBEP8BAQEgASEBFwEWASEBFAECAQcBAwEiAQkCIwEHAQER/wEBAQUBIQEXAh8BEAEJASQBFgEUAQkBFQEIASUBARH/AQEBDwEHARcBFgEeARgBEAEmAQMBEgEJASQBIAEBEf8BAQEcASEBJgEXAh8BGAEIAQ8BBgEPARIBARP/AQEBJwElARIBIQIXAR4CFAEGASgBART/AgEBJQEcARYBKQEnASoBAwEgAQER/wEABf8IAQP/ASMM/wEA+QH/"),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "crystal",
        name: "Crystal",
        description: "A simple crystal with latent magical properties.",
        tags: ["crystal", "enchanted"],
        image: decodeBase64ToImage("LnWjq2+fqpa+yYGstHmnro20wV+buFqYs36rvYq5y3yptXqpuz6Gqzl8n2aPnYCyv1WZvFGKpkZtfkh9k06TtHSiopS2wGKlxWuiuU6AmhtZfkGOtmuCo7PMzMfQz7rR1mimw3uxx4Cfn0aMrLHGzF6evXiov3urwYa/xHimszxxiXWptIezvpS7xa8B/wEAAQEd/wECAQMBBAEFG/8BAgEFAQYBBwEIAQkZ/wEKAQIBCwEMAQ0BDgEPAQAX/wEKAQcCBgEQAREBEgETARQBARX/ARUBFgEXAQwBGAIJARkBGgEbAQsBHBT/AR0BHgEfARABIAEJASEBFAENARgBAgEiFP8BHQEeAR0BFAEgAQkBIQEjAQ0BGAECAQ4U/wEdAR4BJAEQASUBCQEhASMBGgEYAQIBIhT/AR0BHgEkARQBIAEJASYBGwENARgBCQEiFP8BHwEeASQBFAEgAQkBJwEjARoBGAEJAQ4U/wEdAR4BJAEQASABCQEhASMBDQEYAQkBDhT/AR0BHgEkARABIAEJASEBGwENARgBCQEiFP8CHgEkARABIAEJASEBIwENARgBCQEAFP8CHgEkARABIAEJASEBIwENARgBAgEoFP8CHgEfARABIAEJASEBFAENARgBAgEoFP8BKQEWARcBJQEJAQIBIQEZARoBGwEPASIV/wEKASUBIQEIAQYBEQESASoBIwErF/8BCgEkAQgBDAENAQ4BCwEOGf8BJAEWAQYBBwEsAS0b/wEtAQoBKQECHf8BAAEErwH/"),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "faerie_charm",
        name: "Faerie Charm",
        description: "A delicate charm that sparkles with fae magic. It might grant wishes... or mischief.",
        tags: ["jewelry", "fae", "enchanted"],
        image: decodeBase64ToImage("K5CQkHJycnd4d6Ogno2MiVVXWe3o22doZ+3d1dLBvJssZNE6fuGFs+mPu+uzx9SBrNdNieR6mdWAuMpGh+Kbo8VijcM8ftdVgd5ilt+BrdhLgdY/e+J8rco3es0yb86QlNQxdeWgo1UAVdpVjVQZNYAAQNldh9dajMorbrwoa78mZq4B/wEAAQEBAgEDHP8BAwL/AQMc/wEBAv8BARz/AQQC/wEEHP8BAwIFAQMW/wMGBP8BAQEHBP8DBhD/AwgBCQL/AQoCCwEKAv8BCQMIEP8BDAENAQ4BCAEPAf8BCwIQAQsBEQESAQgBDgENAQwQ/wEMBA0BDwELAhEBCwEMBA0BDBD/AQ8EDQEMARMCFAEVAQwEDQEPEf8CDAINAQwBFgIXAQsBGAEMAQ0CDBP/AQ8BDAEZARMEGgEbARwBDAEPFv8BHQELARECFAERAQsBHhf/ARQBHwEVAR4CIAEeASEBHwEUFv8BHwEhARQBHgIgAR4BHwEhAR8T/wEiAgsBEAEjAQsBEQIaAREBGwEjARACCwEkEP8BJQELASMDEQEmAQsBGwEmAxEBIwELASQQ/wElAQsBJwMRARsCKAEbAxEBJwELASQS/wEWAwsBHgIpAR4DCwEWGf8CHh7/ASoBKc8B/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "talking_toadstool",
        name: "Talking Toadstool",
        description: "A sentient fungus with a penchant for dad jokes and bad puns.",
        tags: ["fungus", "enchanted"],
        image: decodeBase64ToImage("MP+AQNyUYuCIUs6BXrNyXoN8ev/Mmd59QdppPsNTQMFrXqlQR35aWN6hgcm+qtNzWMpEJrM6K7usmXZxc3xjbc2giKhfX5ZPTWU7THdHVl9XX9LJuI03N41oY1MyRmxXYTMnLv///8qAT8aQabtNM6A2M6+ikGRnbU9IUnE2PaZjTD5ATlBZaTA9UVxAQD9KXkz/AQABAQECAQMDBAEFFv8BBgEBAQcBAgEIAQkBCgELAQQBDAEFE/8BBQENAQcCCAEOAQ8BEAERAQsBEgIMARMBFBH/AgEBCAEQAggCEAEVARYBFwIYARkBGgETDv8BAAEHAQEBDwEQAQMBGwEJARABCgESARcBHAEdARQBGAEeAR8BEwEgC/8BIQEiAQcBDQEJARABIwEDAhABEQELAhwBGQEfAx4BHwETCv8BAwEiAQcBAQEDAhABJAMQAhEBJQEmARkEHgEfARoBJwj/AQ0BAgEIAQ0BCAEQAQ8BCQEQAQkBIwIRAiUBBQEYBB4BGgEoARoBJwf/AQMBIwEIARUDCQIQAQgBFQEkAiUBHAEpBx4BKAEfB/8BBAETASoBEAEkAQsBJAERAQsBCAEkARABEQElARwBKQceASsBLAj/AR0BGgEZASgDKwEtASsBLgMrBi0BKwEvASsBLBD/ARoBKwEuAS0BJwEsAS0BKwEtAS8W/wETARoBDAIFASwBLwErAS8BLRf/ASwBEwImAScBLAItGP8BJwIFAhMBLAEtAS8Y/wIFARMCJwEtAi8Y/wEvAgUBEwEaAS8CLRj/AS8BEwEnARMBLwItAS8Y/wEaAiYBJwQvGP8BJwIOARIBEwIsAS8Y/wEnAiYBBQEnAy8Y/wEaAiYBEwQvGP8BJwIOARIBEwEsAi8Y/wEnASYCBQEsAy8Y/wEnAiYBJwIvAS0BLKwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "faerie_dance_shoes",
        name: "Faerie Dance Shoes",
        description: "Enchanted shoes that make you dance like a faerie... whether you want to or not.",
        tags: ["footwear", "fae", "enchanted"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "faerie_blade",
        name: "Faerie Blade",
        description: "A elegant, ethereal blade that whispers secrets of the fae realm.",
        tags: ["fae", "enchanted"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "gossamer_mail",
        name: "Gossamer Mail",
        description: "Armor woven from faerie silk, light as a feather but tough as dragon scales.",
        tags: ["armor", "fae"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "enigmatic_bauble",
        name: "Enigmatic Bauble",
        description: "A curious trinket that seems to change its appearance when you're not looking.",
        tags: ["accessory", "enchanted"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "goblin_leader_hat",
        name: "Goblin Leader Hat",
        description: "A crudely made but surprisingly fancy hat. Wearing it might make you feel bossier.",
        tags: ["headwear"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "arcane_tome",
        name: "Arcane Tome",
        description: "An ancient book filled with knowledge of the ages. May cause headaches if read too quickly.",
        tags: ["book"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "battle_manual",
        name: "Battle Manual",
        description: "A comprehensive guide to combat techniques. Now with 50% more diagrams!",
        tags: ["book"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "evasion_scroll",
        name: "Evasion Scroll",
        description: "A magical scroll that teaches the art of dodging. Reading it might make you accidentally dodge your own attacks.",
        tags: ["spell_scroll"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "treasure_map",
        name: "Treasure Map",
        description: "A map leading to buried treasure. X marks the spot... or does it?",
        tags: [],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "egg_of_transformation",
        name: "Egg of Transformation",
        description: "A magical egg that temporarily transforms the user. Side effects may include feathers and a sudden urge to cluck.",
        tags: ["trinket", "enchanted"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "potion_of_unpredictable_might",
        name: "Potion of Unpredictable Might",
        description: "A bubbling concoction that grants incredible strength... with a twist.",
        tags: ["potion"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "essence_of_serendipity",
        name: "Essence of Serendipity",
        description: "A vial of liquid luck. May cause spontaneous four-leaf clover growth.",
        tags: ["potion"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "glow_in_the_dark_potion",
        name: "Glow-in-the-Dark Potion",
        description: "A magical effect that makes your skin glow. Great for reading at night, terrible for stealth.",
        tags: ["potion"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "potion_of_liquid_luck",
        name: "Potion of Liquid Luck",
        description: "A golden potion that promises good fortune. Warning: May cause overconfidence.",
        tags: ["potion"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "fireproof_apron",
        name: "Fireproof Apron",
        description: "An apron that protects against fire. Perfect for dragon-fighting or extreme barbecuing.",
        tags: ["armor"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "harmonic_charm",
        name: "Harmonic Charm",
        description: "A musical charm that resonates with magical energy. May cause spontaneous singing.",
        tags: ["jewelry", "enchanted"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "rhythmic_boots",
        name: "Rhythmic Boots",
        description: "Boots that keep perfect time. Walking becomes dancing, running becomes a musical number.",
        tags: ["footwear", "enchanted"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "novice_whistle",
        name: "Novice Whistle",
        description: "A beginner's musical instrument. May summon woodland creatures... or annoy them.",
        tags: ["trinket"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "laughing_lute",
        name: "Laughing Lute",
        description: "An enchanted lute that finds everything hilarious. Your performances will always have at least one fan.",
        tags: ["enchanted", "instrument"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "bardic_microphone",
        name: "Bardic Microphone",
        description: "A magical microphone that amplifies your voice and charisma. Use responsibly.",
        tags: ["instrument", "enchanted"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "mysterious_artifact",
        name: "Mysterious Artifact",
        description: "An object of unknown origin and purpose. Probably important, definitely mysterious.",
        tags: ["artifact"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    {
        id: "rubber_chicken",
        name: "Rubber Chicken",
        description: "A squeaky toy that's inexplicably part of your inventory. Maybe it's a secret weapon?",
        tags: ["trinket"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
    // Cut

    {
        id: "insight_potion",
        name: "Insight Potion",
        description: "A burst of arcane knowledge that expands your mind... temporarily.",
        tags: ["potion"],
        image: decodeBase64ToImage("RlUqKmAuLl8uLjQeKSUXJU4sN00sMk0qMjQcJyUVJxQUJ2IqKmAsLL53K96eQRg0LGEsLF8sLCUVKCMVJkkkJE4qMkwsMqUwME0rMjQbKBUcKmMuLk4rM9qGPs9XPHUkOBIbJGAqKhUdKCIRKiQVJ2ItLSMSIxUdKSAwMEwvLyQVJiQSJGYzM2EtLRUdJxYcJxYdKBUcKTsUJ18tLU4rMjQaJxoaGl4tLSQUJmInJ2AtLU0rM2ArKxcXF1otLYhLK2AwMF4vLyIRIiIUKCMVKCAgIIwB/wEAAQEDAgEDAQQZ/wEFAQYDBwEIAQkBChf/AQsBDAENBA4BDQEIAQ8V/wEQAREBDAENAg4DDQEIARIBExL/ARQBFQEWAgwBDQIOAxcBGAEIARkBGhH/ARsBHAENAw4BHQEeAhcBHgEOAR4BHwEJASAQ/wEhARgBDQEOAg0BHgMXAR4BDgEeAR8BIgEjEP8BIQEYAQ0BHQcXAQ4BHgEfASIBIxD/ASEBGAENAR0BFwEIASQDCAEYAQ4BHgEfASQBIxD/ASEBGAEXAR4BFwIIARcDDQIeAR8BJAEjEP8BJQEHAR8CFwEIARgBHgIOAQ0BHgEXAR8BIgEmFf8BIgEYAg4BHgMXAR8BJwEmE/8BKAEpAQwBGAEOAR4BDAQIASoBKxT/ASwBLQEYAQ4BFwEMASQBLgEvATABMQEKFP8BLAEtARgBDgEXAQwBJAErGP8BLAEtARgBHgEXAQwBJAEyGP8BFAEzATQCDAEIASQBMhr/ATUBCAMkATYZ/wEsATcBEQEkATga/wE5AToBOwINATwBJwE9GP8BPgEMARgCDgE/ASIBKxj/AUABLQEYAg4BPwEiASsZ/wFBARUCGAEIASIBQhr/AUMBIgIqAUQBRYwB/w=="),
        unlockRequirement: [],
        actionIds: []
    },
];