import { Weapon } from "../ic-agent/declarations/main";
import { decodeBase64ToImage } from "../utils/PixelUtil";

export const weapons: Weapon[] = [
    {
        id: "corrupted_branch",
        name: "Corrupted Branch",
        description: "A twisted branch that has been corrupted by dark magic.",
        actionIds: ["venom_strike", "entangle"],
        image: decodeBase64ToImage("L1VVVVtOTzsqN2dWVlJGSHRmYEg7QYBmdCcnJ2lcXJOEdDIcMCsaKjomLG5XYKabikAmQV4jcE4nVGRGYkQlSXkpi2koeGQ9Z5Q2ro4tq4UpnUQeUXo8foxrgZsmuao1xognr5UmsbBLwalEu5hCoXhRc5YurYcwjmFCVU01RHMzeT4eSEwwTSYTJhISJNkB/wEAAQEBAgL/AQMBBBj/AQIBBQEEAQIB/wEGAQcBAhf/AgUBBAEIAf8BBwEFAgYW/wEJAQoBAwEGAf8BCgEDAQYBAwEGFv8CBQECAQEBBQEBAQsBDAELAQwW/wIFAQYBBQEEAQ0BCwEIDf8BCgICCP8BBQEHAQkBBgELAQgP/wEKAQYBAgj/AQUBAQECAQ0BCw//AQoBBQEGBf8BBgEOAgoBBQECAQsD/wEIDf8BCgEFBv8CCgEFAQMBBgEMAv8DDQECDP8BBQEDAQkCBQEAAgUBBwEJAQYBDQEMAf8CDQELAQwBDQ3/AgoBDwEFAgMBAQIEAQIBCwINAQICCwEIDv8BCgEPAQoBCQEEAQYBAgEGBAIDDQELDf8BCQH/AQoBDwEKAQQCAgEQAxEBEgELAQIBDQEIAQsM/wIKAQEBBQIKARMBEQEUAREBFQEWAhIS/wIKAQYBDwEKARcBGAEVARkBGgEWARsCBgECEP8BAAEHAQUBHAEdARwBGAEeAR8BIAEhAREBCwINEf8BBwEKARwBIgEjASQBJQERARkBJgERAQIBDAEIAQ0P/wMKASUBJAEnASQBJQEQARYBJgEbAQwS/wIPAQoBAwEoASkBKgEXAQIBEAESASsBCwEMEv8CCgEFASwBAgENARQBEAECAQsCDBT/AgMBAgEQAQ0BBgEQAQsCLRb/AQUBBgMCAQYBCwItF/8BBgICAQsBEAELAS0BLhj/AQIBEAECAQsCLQEuGf8BBgIMAi0BLhr/"),
        unlockRequirement: { none: null }
    },
    {
        id: "iron_sword",
        name: "Iron Sword",
        description: "A sturdy iron sword, reliable in combat.",
        actionIds: ["slash", "defensive_stance"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: { none: null }
    },
    {
        id: "apprentice_wand",
        name: "Apprentice Wand",
        description: "A simple wand for novice mages.",
        actionIds: ["fireball", "frost_bolt"],
        image: decodeBase64ToImage("QmYzM0wpNEwqM1EuLntHQnpIQa13V18rK2EqKmAsLE8sMF8tLU0rMkwqMk0qMkcqOXtIQk4qM0oqMHpHQnlIQU0sMkkkN2EsLE0rMyoqKl8sLDMdJ0QiM0kkJGEtLU0zM3pJQU4rMnpHQU4nO3hJQkstLXxIQHtIQXxJQkwrMnlHQ04sMl0uLntJQkwsNGMqKkwsM04qMU4rM04qMlUqKnpIQDMaM6x3V3lIQEYuLnhHQE0rMUwpMHpJQjsUJ2AtLUMbNk4sNzr/AQABAQECAQMc/wEEAQUBBgEHG/8BCAEJAQUBCQEKGv8BCwMFAQwa/wENAgUBDAEOAQ8Z/wEIARABBQEJAREa/wESARMCCQEMGv8BAgEUAQUBDgEVARYa/wEXAQUBDgEYGv8BGQEQAQUBGgEbARwZ/wEdAR4BBQEJAQwa/wEfASABBQEOASEb/wEiAQYBCQEYASMa/wEkAQkBBQEMASUa/wEmAScBCQEMAQMa/wEoAQUBCQEpAQ8a/wEqAQYBCQEMASsa/wEsAS0BCQEMAS4a/wEvAgUBDAEwGv8BJQIFAQkBMRv/ATIBBQEJATMBNBr/ATUBBgEJATIBNBr/AScBBgEJAQwBNhr/AQsBNwEFASkBHRr/ATgBBQEJAQwBORr/AToBBgEFATsBHxr/ATwBPQEFARUBPhr/AToBIgEFAQ0c/wE/AQUBDgFAHP8BQQEOATM7/w=="),
        unlockRequirement: { none: null }
    },
    {
        id: "iron_dagger",
        name: "Iron Dagger",
        description: "A quick and sharp iron dagger.",
        actionIds: ["stab", "fury_swipes"],
        image: decodeBase64ToImage("LignMz89SENDUSwrOSckMXV9hKOqp3R8gTExQGRqc1NVXyYaJjk3RWNob0hLVjEuPGJkcE9RXiQhMEdFT3BzflZYZVxea0dHVFdcaCYiLScUJ0VCTWZodUdKWi8uQE1QWUpMWzIuNko5P1c7PTYxOmhSUm1RUS8kKTo3Q3tmZTsmLEkyNSsiKzorNFr/AQABAQECAQMBBBn/AQABBAEFAQYBBwEIGf8BAAEBAQUBBgEFAQEBAxj/AQQBCQIGAQUBCgEIAQAW/wELAQQBDAEFAQYBDQEOAQwBDxf/ARACBQEGAQUBEQEIAQAW/wESARMDBgEUAQoBDAEDARIW/wETAgYCBQEVAQIBAwEEFP8BBAESAQIBFgEGAgUBCgECAQ8BBAELE/8BEgEUBAYBFAEKAQwBDwEDAQsM/wESAQIBDgEBAQsB/wESAQIBFwEFAQYBBQEGARYBEQECAQMBBAELDf8BAAEFAQYBGAEZAf8BBAEFAgYCBQEUAREBAgEIARIP/wEaARsBHAEFAQ4BCAEWAgYBBQEUARYBHQECAR4BAwEZEP8BAAEIAQkBBgEfAQUBBgEFARwBCgEOAQEBCAEAAQQS/wESAQgBHAEFASABHAEVARABIAEMAQ8BABX/AQQBCAEdARYBFwEOARcBDAEDAQABGRX/AQQBAAEhAQwBFwEOAQEBDwEAARkV/wEEASICIwEkARwBBQEOAQABGhT/ARIBEwEbASUBJgEjAScBDAEWAQ0BBQEoFP8BBAEHAQYBKQEjASoBIQEkAQgBHAEGAREBBBH/AQQBEgEhAR8BBwEUASEBGQESARkBEgEIARABBgEKAR4O/wESAQsBAAEEASMBKgEPAREBAwESA/8BBAEeAQkBBQEMDf8BBAEWAQ0BIgElASYBKwEsAR4BAwEABP8BAAECAQUBDAz/AQQBAAEFAQYBFwEtASMBLQIEARIBCwT/AQsBAwEMAQgM/wECAQYBFwEYAQcBIQEnAgQX/wEIARQBBQEeARUBEAEAAQsY/wESAQgBGAECAQgBIAEDAQsZ/wEaAg8BBAIAG/8BCwISO/8="),
        unlockRequirement: { none: null }
    },
    {
        id: "short_bow",
        name: "Short Bow",
        description: "A compact bow for quick shots.",
        actionIds: ["piercing_shot", "rapid_shot"],
        image: decodeBase64ToImage("aSYaJhoaGiYWJmEsLHhGQTMbJWAsLE0rMiQSJDUbJU0qMSQkJDkcJk0qMl8sLGIsLCoVKioqKjQbKDQcKHpIQTIeKBwcHE4qMk4sMjMcJyQVJzMbJjMcKDQcJyQWJiQWJzccKTYbJk0rMSUWJTEYJBcXFzUdKCAgIK13V0sqMiQYJDMdJjQeKTMdKE0sMiMVJyoOKjceJDQdJ04rMyMWKC0eLTQbJyMVKiIUKDQaJzYfJygbKCYTJjUcJyYVJjMcJjMaKikUKTMdJzQaJCIUJzQeJXlIQTEZKTYbKDcbJMCUczYdJzUbJiAVKiQVKDMcJTQaJTYcJjMaMzUcKDMdJDQbJigYKDMaJiMUKDMbJwAkJCUVJyMWJjIdKDQdKCQWKDUaKDUbJzUeKjQcJiMUJ613WCQUJ1EuLi4XLhz/AQABAR3/AQIBAwEEHf8BBQEGAQcBCBz/AQkCChv/AQsBDAENAQ4BDxb/ARAB/wERAf8BEQESARMBFAEHARUU/wEWARcBFAEYARkCGgEbARwBEhb/AR0CFAEdARwBHgEfAhoBIBL/ASEBBwEiAR0BFAEGAR0BIwEkAf8BJQEaASYBJxL/AQ0BKAIUAQcBKQEqA/8BKwEsE/8BLQEuASgCHQEvATAC/wELATEBMhP/AQICFAEzATQBNQT/ATYBNwE4Ev8BOQEGARQBBwE6BP8BOwE8AT0BPBH/AT4BMgIUAT8BEAT/AUABHQE2ASAR/wFBAUIBBgEUAQcBQwT/ATsBRAEdEv8BRQEuAUYBKAEHAUcF/wEyAUgBSRL/ARoCSgEUAUsF/wETAUwBTRP/ARoBFAEHAR0BSwX/AU4BTxT/ARoBFAEdARIBJwP/AVABEwFRAVIU/wEaARQBHAE9A/8BUwE9AUEBERT/AVQCFAEyA/8BUwFVAVYW/wE9ARQBNgFXAv8BWAEaAVkBWhb/AT0BFAEdARAB/wFEAVsBXBj/AV0BHQEaARABXgEZAVwZ/wFfARoBYAEAAWEBYhr/AV8BHQFgAT0BMhf/AWMBWgH/ATsBEgEUATIBWRb/AUgBZAFlAR0BZgFbARoBYQEWF/8BQQEaASgBFAEHAR0BMgFSGf8BZwMdATIBaBv/ASYBMgEMO/8="),
        unlockRequirement: { none: null }
    },
    {
        id: "oaken_staff",
        name: "Oaken Staff",
        description: "A staff carved from ancient oak, resonating with nature's power.",
        actionIds: ["wild_growth", "natures_wrath"],
        image: decodeBase64ToImage("O3tIQXpIQU4qNEkxMa12V00rMk4sMr+PcK13VzMcJ0wsNF4qKmAsLE0sMrR4WnlHQTQcJ00qMlU5OV8sLDQdJ3tKQDQbJ2ArK04sMTQcJlAwMIhLKzccKTYbKDMzMzQbJk0zM04uNE4rMjUcJ0wqMzUcJjMdJkwrMjggKEoqNTMaKk0qMTEZKUopMXdERDQdKK12WzIdKDMfKTUgKk4qMq53WDMaJjUdJjUbJ04nMT0fMzD/AQABAQECHP8BAwEEAQUBBhv/AQcBCAEBAQUBCQEKGf8BCwIMAQUBAQEMAQ0Y/wEOAQ8CAQEMARABBQERF/8BEgETAQUCAQIMARABDAEUFv8BFQEBAQwDAQIFAQgBFhb/ARcBCAEBAQUEAQEMARQW/wEYAQUBAQEIAQUBDAEBARABGQEaF/8BGQEQAQEBGwEMARABCQEcGP8BHQEQAQUCDAEFAQ0BHhj/ARoBHwEFAQwBBQEQARQBIBn/ASEBIgEFARABIwEkG/8BFAMQHP8BJQEFAQwBEBz/ARMBAQEFASYc/wEkAScBDAEFHP8BKAEBAQwBKRz/ASoBAQEMASsc/wEsARcBAQEFHP8BLQIMAQUc/wEuAQwBEAEvHP8BMAEBARABMRz/ARcBDAERATIc/wENAgwBMxz/ATQBFwEMATMc/wE1AQwBEAE2HP8BNwIFATgc/wEsAhcBORz/ASwBFwEMATIc/wEsAhcBOg7/"),
        unlockRequirement: { none: null }
    },
    {
        id: "iron_mace",
        name: "Iron Mace",
        description: "A heavy iron mace for crushing blows.",
        actionIds: ["smite", "war_cry"],
        image: decodeBase64ToImage("UjpKUDhJUGCAgFdydzlLUSIzMztOTiAtNldzdzlJUDhKUVdxdzZNTTlKUVZydjlKUIGXliMsNSAuN6i1sjpLUDlLUAAzMyQkJCAuNjhKUCoqQDxLUjlHVSQxPYGXlSIsNldydSAvNx8uN1ZzdzhKT2QuLh4tNCAtN0lJSWQsLIhLLIhLKk0rMjpJTyEsNzpIUohLK2AsLDQcJ2ExMUwqMohMK18sLE4qMyoqKodMK04rMVp1dThLUDMcJzQbJlUqKodLLCEtNyYzMzUcJx4tPGYzM0wrModMLF8qKkwvLzlJT00sMTlJUTlKTypVVVhzdiAvNoCVlTb/AQABAR3/AQIBAwEEAQUBBhn/AQYBBAEHAQgBCQEKAQsBDAENFv8BDgEPAwMBEAIDAQABAxT/AREBEgIPAgMBEwEQAQMCDwEUFP8BFQEQAwMDEAIDAQ8BDQEAARYS/wEXARgBDwMQAQMBDwIQAQ8BAwEZARoT/wEbAgMFEAIDAQ8BHBP/AR0BHgEDAQ8CAwIQAgMBDwEfFP8BIAELAg8BAwEPAQMCDwIDAQEV/wEhAQMBFQEiAQ8BAwMPASMBJBT/ASUBDwEQAQ8BJgEnAw8BDQEoFP8BKQEqASsBLAEtAf8BLgEbAgEBLxT/ASkCMAExATIa/wEzATABKwExATQa/wEpATUBMAE2ATcBOBn/ASkBOQErATEBOhr/ATsBPAIxAT0b/wEJARABDwE+Gv8BPwFAATEBDwFBAUIa/wFAATABMQFDAUQZ/wFFAUABMAExAUYb/wFHASsBMQFIGv8BRQEqATABMQFGGv8BSQFHATABMQE0Gv8BSgEPAjEBPRv/AQ8BEAEVAUsb/wFMAU0BDwESG/8BTgFPAQgBUB7/AVE9/w=="),
        unlockRequirement: { none: null }
    },
    {
        id: "basic_lute",
        name: "Basic Lute",
        description: "A simple lute for aspiring bards.",
        actionIds: ["regenerate", "war_cry"],
        image: decodeBase64ToImage("UyUUJSMVKDIdKGAsLHpIQSQXJyQWJq13V8CUcyQUJzQcKIhLKzQcJjMZKU0qMk0rMjQcJxwcHDMcJSUTJU4rMzYdJ00rMSIVJiUWJSMVKmEtLRIeKk0qMSQUKDMbJzcbJCYWJjUcJzMdJCQSJK13VoBQQBozMxcfJzUcJkwrMiMUKA4cKiMWJyQVJyMUJioqKjQdJyUWKCYTJte1lK13WCQWJyUWKTMbJhQdJyIRIjYbJnpIQCcUJyIUKDsUJxcXFyUVJxISGxoaGjMdKBQUJzQaJDUdJk4sMiAQICQYJCQVKDUdJyEWLCQVJjMcJyQkJCUWJiMWKCAgICP/AQABAQEAHP8BAgEDAgQBBRr/AQYBBAEHAQgBBwEEAQkY/wEKAQQDCwIHAQQBDAENFv8BDgILAQ8BEAEPAQcCBAEMAREV/wELAQMBEAESAf8BEwEUAgQBBwEPARUU/wELAQMBDgESAv8BDAEDAgQBBwEWARcT/wELAQQBAwEYAv8BGQEQAgQBCwEEARoBGxL/Ag8BHAT/ARsBEAEPAQsBBAEHAQ8BHRH/Ah4BHwX/ASABIQEPAgQBBwEEASIZ/wEjARABDwEEAQsBBwEkASUBJhj/AScBKAEEAQcBCwIHASkBKgErF/8BIAEKAgQBBwIEAQ8BLAEtAS4BLxX/ARsBEAEDAgsBBwQEATABMRX/ATIBLQEQAgsBBwIIATMBBwE0ATUBNhT/ATcCBwIEBggBBAEwATgS/wE3AQcKCAEEARABORH/ATcFCAEHAQQBDwEEBAgBDgE6EP8BKAEHATMDCAMEAQcBBAIIAjMBOwEdD/8BPAEtATMDCAEHAwQBBwMIATMBCAE7AT0O/wE+AS0BMwUIAwQECAIzAQQO/wE/AUABBAsIAgcBMwEID/8BQQEPAQQBMwgIAgQCCAEzEP8BLQEPCAgBBwEPAQcDCBD/ATcBDgEEAQcECAEHAQ8BBAEHAQgCBwEEEP8BIwEPAQQBAwIEATMCCAEEAQcDCAEEAQ8Q/wFCAUMBDwILAQcDMwIIAjMBBAEHAS4R/wFEAUUBRgYPAQcBBAEPAQ4BRwFIE/8BSQFKAQ8HBAFLAUwV/wEjAQkCTQEQAQMBTgFNATUBSBj/Ak8BGAFQAVEBUgT/"),
        unlockRequirement: { none: null }
    },
    {
        id: "wooden_staff",
        name: "Wooden Staff",
        description: "A sturdy wooden staff for martial arts.",
        actionIds: ["double_slash", "defensive_stance"],
        image: decodeBase64ToImage("K04sNGAsLE0qMjIdKL53K9qGPohLLDYfJyMXI00sMohLK18sLK13V3lIQTMfKSUXJSUWJyQUJjQdKHpIQSQUKWAtLTUcJyUUKE0rMnpIQBUVFTQcJ4dLKzMdJyUWJTQbKE0rMWErKy4XLjMbJ0wqMicUJ2ArK3tIQTYbKCAgIHpHQU7/AQAEAQECGf8BAwEBAwQCBQEGAQcW/wEIAQkBCgEEAQsBAQEKAQwBBQENAQ4V/wEPAQEBCgEBARABEQESAQoBBAEFARMV/wEUAQEBCgEVARYBEwEXARgBBAEFARkV/wEaARsCCgEcAQkBAgEKAQQBDAEdFv8BHgEfAgEBIAMKASEY/wEiASMBHwMKASQBJRr/ARgBCgEEASYc/wEYAQQBJwEoHP8BGAEEARUBKRz/ARgBBAEBHf8BGwEEAQEd/wEbAQQBAR3/ARgBCgEBHf8BGAEKARMd/wEYAQoBKh3/ARsBCgETHf8BGwEKAQEd/wEYAQQBFR3/ARsBCgEBHf8BGwEKARMd/wEYAQoBEx3/ARsBBAEBHf8BGwEEARUd/wEbAQQBAR3/ARsBBAEBHf8BGwEMAQEd/wEYAQoBAR3/ARgBCgEBDf8="),
        unlockRequirement: { none: null }
    },
    {
        id: "mechanic_wrench",
        name: "Mechanic's Wrench",
        description: "A versatile wrench for tinkering and bashing.",
        actionIds: ["thunder_strike", "fortify"],
        image: decodeBase64ToImage("Sqa1sVZzeICqqoKWlqi2s1dydzlKUB0xO4CVlYGXliAuNiIwNR8tOCIzM6S2tiAuNx8vOai0sSEuNhUeJ4CYlai1shYeKYCWlhEiIoGWlh8uNxQdKSAvNhUdKRUdKBQeKRgeKhUbKoCSkhQcKICXlx8uNhoaGoKXliAgIBcXLoCYlCAuOBQfKYKXl1dzdxcdJxYdKKqqqoCAgMTRy6m2s4CYllZxdyAqNf///6q2sKe0siAtNxQdKKazs6e1sqm0sRczLSIvNhcgOBcjIxEaKiEuNxYdKRYdJyEvNxUcKDb/AQABARv/AQIBAwEEAQUBBgEHGv8BCAIJAf8BCgELAf8BDAENFv8BDgIJAQUBDwP/AQUBEBb/ARECCQEFARIC/wEFAQYBExb/ARQBFQIFAwkBBQEPARYW/wEXAQUCBgMFAQYBDwEYFv8BGQIGAQUDBgEaARsW/wEDAQUBBgEFAgYBDwEaARwW/wEUAQUBBgEFAQYBDwEdAR4BHxb/ARkBBQEGAQUBBgEaASAY/wEUAQUBBgIFAQ8BIRj/ASIBAwEGAgUBDwEjGP8BCAEkAQUBBgEFAQYBJQEmGP8BJwIGAQUBBgEaASgY/wEZAwUBBgEeASkY/wEqAQUBBgEFAQYBKwEsGP8BLQEuAQYCBQEPAS8Y/wEiARkCBgEFAQ8BMBb/ATEB/wEyARkBBQEGAQUBBgEdFv8BMwE0ATUBNgEFAQYBBQEGAQ8BNxT/ATgBOQE6ARUCCQEGAQUBBgE7ATwV/wE9AT4BCQEFAQkDBQEPAR4W/wE/AQkBBgEKAQ8BCQIFAg8W/wE+AQUBCgEvAUABBgEJAQUBBgFBFv8BNgEGAUIBQwEyAQUBCQEGATsBExb/AUQBRQL/ARkBCQEGARoBRhr/ARcBBQEGAQ8BRxv/AUgBGgFJAR9X/w=="),
        unlockRequirement: { none: null }
    },
    {
        id: "bone_staff",
        name: "Bone Staff",
        description: "A staff made from enchanted bones, radiating dark energy.",
        actionIds: ["life_drain", "shadow_bolt"],
        image: decodeBase64ToImage("Pj0pUioqVUAnUj8mUioqKj8mTz8nUUAqVUAoUEAnUUAnUEEmUEAgUIGXlqi1sldyd0MsTkEnUAAAAEkkSUYuRkAoUTlKUE0rMjYbKE0sMioVKjQcJ3pIQR4tPCQVJzUbJzMbJTUcJ00rMRMTIDQbJjMdJ2AsLCYaJhEUICQVKEwrMkwqMiQUJx0sOk0qMiIRKg0UIhAUH18sLDMdJg8VHhQeKDIbJygYKBMTHyQUJjQcJiIsNhUeJyMUJi//AQAe/wEBAQIBAxr/AQQC/wEFAf8BBgL/AQcY/wEIAgkC/wEKAQkZ/wELAf8ECQH/AQkW/wEMAwkBDQIOAQ8BCQH/ARAX/wEJAQ8DDgENAv8BERf/AQYBDwESAQ0BEgEPAgkW/wEHAf8CCQEPARICDwEJAf8BExj/AQYBDwINAgkBChj/ARQBFQEWARcBCQEKGv8BGAEZARYBFxz/ARoCGwIcARcb/wEdARkBFgEeAR8c/wEgASEBGwEiHP8BIwEkARwBJRz/ASIBJgEXAScc/wEbARcBKB3/ASkBHgEoHf8BKgErASwBEhz/AS0BGwEuAS8c/wEwATEBMgEzHP8BNAEbARcBNRz/AR4BFwEeAQQc/wE2ARsBNx3/ATgBJAE5Hf8BOAEiATod/wEuARwBDwE7HP8BIgIPHv8BPAE9L/8="),
        unlockRequirement: { none: null }
    },
    {
        id: "crude_daggers",
        name: "Crude Daggers",
        description: "Simple, roughly-made daggers favored by goblins for their quick attacks.",
        actionIds: ["fury_swipes", "venom_strike"],
        image: decodeBase64ToImage("bWZmZnFVOTlHVVdyd3pHQUwsMoBJSXpIQTlKUE0rMk4sN2ApKXlHQmAsLE4rMlUqKoCqqjtHTWYzM4dJKjUbJjsUJ1UzMzlJUDpKUMaOcYCVlTZRUU0qMjMcJyoVKk8tM1VzeHpHQE0qM0wpNE0rMXlJQ1AsM0wqMXtIQUwrMkkkN3xLPjQcJ0wpM8bGxqe2sYGXljUcJlhzdr+UcoiZmYhLKk4rM0stMszMzMjNzai1sldxd3lHQ3lKQUwqMjYdJ6K5ucfPy8fOzDhKUE8qM7+/v8jQzMfPzE4qMsfQzMbPzISUlMjOyzQdJ8jPz8jIyMbOzk0sMk0zM8bQ0MfPzTckJP///7/Pz08sMMTRy8nOzsLOzsbOzLa2tsjPzKe2sjpLUICfn1hzeEwqM8PS0sfQzWCAgEkkJICYlFdzd04sMVVVVTNNTZIB/wEAAQEd/wECAQMBBAEFG/8BBgEDAQcBCAEJAQoa/wELAgkBCAEJAQoa/wEMAQQBDQEJAQ4BDwP/ARABAwEREv8BEgETAgcBCQEUARUD/wEWARcBBwEYAQ8M/wEZARoBGwL/AwcBHAEdAR4E/wEcAQkBCAEJAR8M/wEgASEBIgEPASMBBwENARwBJAEeBP8BJQEHAgkBHAEmDP8BHwEnAQgBKAIJARwBKQEqBP8BKwIHAQ0BLAEtDv8BLgEvATABCAEJATEBKQEyATMBNAH/ASUBBAE1AQ0BNgE3Dv8BOAE5AToBMAIIASkBCQEHATsBPAE9AgcBDQE+AT8O/wFAAUEBQgE6AwMBCQEiAQkBNgFDAQcBHAENAT4BRA7/AUUBRgJHAwMD/wFIAUIBMAEIAQkBLAEFDv8BLgFJAUoBOgEwAQMBMAEIAv8BSwFMAUIBMAIIASkBTQ7/AU4BRwE6BAMC/wFPAVABRwE6AgMBCAIJAVEBUgv/AVMBVAFHATACAwEIAv8BOAJHAToBAwEwAQMBHAE2AQkBTQFVCv8BVgFKAUcBOgMDAv8BVwJJAToDAwEcA/8BWAv/ATgCRwEwAQMBCAP/AUwBSQE6AjABAwEpEP8BWQFHAToBMAEDA/8BWgFHAToDAwEkEP8BWwFcAUcBAwEJA/8BWgFUAToCMAEDAQkQ/wFdAUcBOgEDASQD/wE4AV4BRwEwAgMBBRH/AV0BXwFgAQgBVQP/AkcBOgEDAQkT/wFhAWIBYwT/AWQBZQEwAQgBCRX/AWYBZwT/AWUBOgEIAVEc/wFoAWkBah3/AWsBbFX/"),
        unlockRequirement: { none: null }
    },
    {
        id: "shadow_bow",
        name: "Shadow Bow",
        description: "A sleek bow imbued with dark magic, favored by dark elves for its precision and power.",
        actionIds: ["piercing_shot", "shadow_bolt"],
        image: decodeBase64ToImage("LypVVRMYJxEXIjEyTy4tUCorSFZYXRsbNhsbLh8hQiIjQFNUdV1fiTU4UzYuMDc3XjAwVx0iNxYbLRwhKjg9VWhqij1AZScrRTI0RTcqKHV2mCcoOioqPx4gMzMqKTktKhIaLBcXFzs9WCknQjkcHCUnL0dERDw8XlpfZCkmKTo8PisrOFJUVikmLignMEH/AQABAQECF/8BAwEEAQUD/wEGAQcBCAEJAQoU/wEDAQsBDAENAQoC/wEOAQkBBwEFAQ8BEAEKAQkBEQEIARICEwz/ARQBCwEVAQME/wEHAQkCFgEEAQkBFwEKARgBEQISAgEJ/wETAQ0BFgEEARQF/wEZARMCAQEIAQ8BAwEaARYBBQEJAQgBEgEbBv8BFwELARwBHQEbAQ0BFwT/AhkBHgICAQgBEAEDAQ0CFgEQAg8BAQX/AgUBDAEPAREBEwf/ARkCHwT/AQUBEQEXARYBDAEaARABFwEHASABIQEFASIBGgEYASMBGwn/ARkCHwEkA/8BEgEKAQUBIwEYAQUBCgEJARIBAQEDAQsBDQERDP8BGQIfBf8BAQISARcBEQMKAhYBEQElDf8CJgj/AQIBAQEKAQ0BFgEnAQoBCQ7/AigBGQEpBv8BIQEpARMCFgEHAhIO/wEAASoBGQEfBv8CKQEqASsBCgEQAQkBIAETD/8CHwEOASQD/wIpASwBKgETAQoBFwEEARIBEw//ASQCHwEZAv8BEwEpASYBDgEpARMBEgEKAQUBEAEIARIQ/wIfARkBKQEtASoBHgEpARMC/wEIAQoBCwEQAREBEhD/ARkBKQMOAS0BEwP/AQEBEQELARABCAESEP8BKQEOAioBKQX/AQEBGwELAQQBBwEID/8BLQEOASoBJgEeARkG/wEEARABDwEEAQoBAQ3/ARMBLQEqAQ4BKQIZAR4BKQT/AhICDwEXAQEM/wITASoBDgEpARMBJAEeAhkE/wEhAQEBEAEPARcBAQr/AQIBEwEdASoBLQEpBP8DHwX/AQUBGgELAQoJ/wEIAQEBHAEVASsBLgETBf8BGQIfBP8BBQELAQ8BCgj/ARIBDQIWAQYBGwESB/8CHwEqASgC/wEpARcCCgb/AQIBEgEIAQsBGgELAgEJ/wEfASYBBgEZASkB/wESARcBDwb/AREBHAEFAQsBFQEiAQEBIAr/ASgBLAEfARkBKQEHARABFgECASEE/wERAgwBFAIBASEM/wEOAh8BGQIKAREBCAESBP8BCgELARYBFxL/AR8BGQEJARABDwEBBP8BCgEjAREBHRL/AR8BJAEHAREBHQESBP8BCgIdAQgV/wEIARMBISL/"),
        unlockRequirement: { none: null }
    },
];