import { Weapon } from "../ic-agent/declarations/main";
import { decodeBase64ToImage } from "../utils/PixelUtil";

export const weapons: Weapon[] = [
    {
        id: "corrupted_branch",
        name: "Corrupted Branch",
        description: "A twisted branch that has been corrupted by dark magic.",
        actionIds: ["venom_strike", "entangle"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "iron_sword",
        name: "Iron Sword",
        description: "A sturdy iron sword, reliable in combat.",
        actionIds: ["slash", "defensive_stance"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "apprentice_wand",
        name: "Apprentice Wand",
        description: "A simple wand for novice mages.",
        actionIds: ["fireball", "frost_bolt"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "iron_dagger",
        name: "Iron Dagger",
        description: "A quick and sharp iron dagger.",
        actionIds: ["stab", "fury_swipes"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "short_bow",
        name: "Short Bow",
        description: "A compact bow for quick shots.",
        actionIds: ["piercing_shot", "rapid_shot"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "oaken_staff",
        name: "Oaken Staff",
        description: "A staff carved from ancient oak, resonating with nature's power.",
        actionIds: ["wild_growth", "natures_wrath"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "iron_mace",
        name: "Iron Mace",
        description: "A heavy iron mace for crushing blows.",
        actionIds: ["smite", "war_cry"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "basic_lute",
        name: "Basic Lute",
        description: "A simple lute for aspiring bards.",
        actionIds: ["regenerate", "war_cry"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "wooden_staff",
        name: "Wooden Staff",
        description: "A sturdy wooden staff for martial arts.",
        actionIds: ["double_slash", "defensive_stance"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "mechanic_wrench",
        name: "Mechanic's Wrench",
        description: "A versatile wrench for tinkering and bashing.",
        actionIds: ["thunder_strike", "fortify"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "bone_staff",
        name: "Bone Staff",
        description: "A staff made from enchanted bones, radiating dark energy.",
        actionIds: ["life_drain", "shadow_bolt"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "crude_daggers",
        name: "Crude Daggers",
        description: "Simple, roughly-made daggers favored by goblins for their quick attacks.",
        actionIds: ["fury_swipes", "venom_strike"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
    {
        id: "shadow_bow",
        name: "Shadow Bow",
        description: "A sleek bow imbued with dark magic, favored by dark elves for its precision and power.",
        actionIds: ["piercing_shot", "shadow_bolt"],
        image: decodeBase64ToImage("UggKFQkKFAoKFAgLE1Zxd4GXliEvNjEZKQAAAAgKFMfPzKi1sgkLFA4ODggIFyAuNx8uNxERERAVH6Td2wkJFAAAJCcUJ1dydwsLFiQWJwASEg0NGh8vOAkJEyIRIiEuODlKUAkJEiQUJgsLFSAvNwgIECEtNyEtNggIGCEuNxUdKAwMFwgIETlKTyQUJyAtNxAQEAwMGCMVJ0AAQAoKEyYaJiQVJxUcKBYdKBQcKCQWKBAUHxAUIAsLFxEVHzQcJyAuOCMVJmAsLAYME3pIQU0rMoGWlhEUHwoKFSQVKCUUKDlKUTMcJ1dydggIFRUdKQwMEQcNFCL/AQABAQECHP8BAwEEAQUBBgEHAQga/wEJAQUBCgELAQoBDAENGf8BDgEPAQsBCgELAQUBEAERGf8BEgIFARMBCgEFARQBFRj/ARYBAQEXAQsBBQETAQsBDwEYGP8BGAEPAQUBCwEFARMBFwEZARoY/wEbAQEBBQELAQUBCwEFARwBHRj/AR4BHwEFAQsBBQELAQUBIAEdGP8BIQEPAQUBCwEFARMBBQEiARgY/wEjARABBQELAQUBCwEXASQBIxj/ASUBJgEFAQsBBQELARcBJwERGP8BKAEpAQUBCwEFAQsBBQEqASsY/wEsAS0BBQELAQUBCwEXAS4BCBj/ASwBLwEFAQsDBQEUAREY/wEhAS8EBQEXASoBMAT/ATEBMgECEf8BKAEPARcBBQEXAQUBFwEUATMBNAEJAgIBBQECEv8BNQEBBRcBNgEXBAsBAhP/ASsBNwIXASoBIAILARcBOAE5AToBOxT/ARgBCQEXASABCgELARcBEAEDGP8BFgEPAgsBFwEgATwBPRj/AT4BIAELARcBIAI/AS4BMRf/ATsBCwEXAUABNAFBAkIBNgFDFf8BIQEBAQsBOwEAAQgBIwE/AUQBRQEuAQIU/wE2AUYBCwFHA/8BSAEuAkQBSQECE/8BSgFLARcBOwT/AQIBTAFEAUUBTQE2Ev8BCAFOAU8BTgX/AUMBNgIXAQUBFBv/AQwBFwEFAS0BUBv/AVEBEgEqAQFC/w=="),
        unlockRequirement: []
    },
];